/* Creación de usuario si está trabajando con BD Oracle XE */
CREATE USER MDY3131_GA IDENTIFIED BY "MDY3131.guia_apoyo"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER MDY3131_GA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO MDY3131_GA;
GRANT "RESOURCE" TO MDY3131_GA;
ALTER USER MDY3131_GA DEFAULT ROLE "RESOURCE";
